version: "3"

services:

  teamCity:
    image: jetbrains/teamcity-server:latest-nanoserver
    links:
      - buildAgentOne
    volumes:
      - "c:/teamcity/logs:C:/TeamCity/logs"
      - "c:/teamcity/data:C:/ProgramData/JetBrains/TeamCity"
    ports:
      - "8111:8111"
    container_name: teamCity
    hostname: teamCity

  buildAgentOne:
    image: jetbrains/teamcity-agent:latest-nanoserver
    environment:
      - server_url=http:teamCity:8111
    volumes:
      - "c:/teamcity/agentConfig:C:/TeamCity/logs"

networks:
    default:
      external:
        name: nat