version: "3"

services:

  teamCity:
    image: jetbrains/teamcity-server:latest-windowsservercore
    links:
      - buildAgentOne
    volumes:
      - "c:/teamcity/logs:C:/TeamCity/logs"
      - "c:/teamcity/data:C:/ProgramData/JetBrains/TeamCity"
    ports:
      - "8111:8111"

  buildAgentOne:
    image: jetbrains/teamcity-agent:latest-windowsservercore
    environment:
      - server_url=http://172.23.175.249:8111
    volumes:
      - "c:/teamcity/agentConfig:C:/TeamCity/logs"

networks:
    default:
      external:
        name: nat